In [2]:
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('seaborn-v0_8-whitegrid')

Hi everyone! Today we are building *Scalebandit*, which will address the problems we encountered in the last lecture.

If you remember back to Lecture 2, we actually made *personalised content* by introducing the concept of <span style="color:blue">states</span>. We now had a row for each different type of user that we wanted to make the best YouTube homepage for. We also remember that this worked perfectly, until we tried to scale it. We discovered what is called the **curse of dimensionality**. As we got exited and added more <span style="color:blue">states</span>, our table blew up, because we had to have a single cell, for each new 'thing' we added, and if multiple things are going to have their own cell, then the total number of cells is all these things multiplied together. So the table exploded in size, becoming hard to fit into our computer memory, and also was really hard to get anything meaningful out of, because of the fact that we needed to actually have insane amounts of data to be sure that we saw each cell, for each specific case (tablet user in France at midnight), several times so our estmiate of that value became something that we could trust. 

This is the wall that the table methods hit. The brain works kind of by **memorisation**. It *needs a separate memory slot (a row in our table) for every single possible situation*. 

Today, we are going to solve this problem by trying to find a method that can **generalise** (i.e., say anything about things that it has never encountered before). 

---

Think about when you learned the gangetabell. One day your teacher said: "tomorrow I'm going to test you with numbers from 0 to 10, so you need to learn this". You go home and you write down a large 2D-table for all numbers that can multiply (e.g., 2 x 3 = 6, 4 x 5 = 20 etc.). So now each answer has it's own cell. Then you try rally hard to hold your hand over every cell and try again and again to remember what the answer is, for each combination of numbers, until you get it absolutely perfect, and you go with a big dick walk to school the next day. You know *all the answers*. This is a bit like what we are doing with our table in the last lecture. We had our table, and if you wanted to know the value of showing a viral thing to a new viewer, you just looked it up: `belief_table[0, 0]`. If the entry wasn't there, you had no idea of what the value was. 

However, there is another way. Imagine you instead built a device, that for any two numbers you put in, gave you the answer. So now when the teacher gave you the numbers 4 and 5, you used your device it gave you 20 back, which you passed on as your answer to the teacher.

This is exactly the conceptual change we are going to make today. We **want something that takes our state and gives back the value for showing each different thumbnail**. We don't want to remember it, we want to be able to calculate it on the fly. Even for states we haven't seen before.

Formally, we can say that we want: `values = f(state)`

Let's give this <span style="color:LightCoral">function</span> a name, so that we can talk about it. Let's call it our *Value function approximator*. Because we want the value, we use a device called a function to return it to us, and approximator because we give the thing a little slack, so that it doesn't have to be perfectly accurate at first, but we can kind of make a reasonable guess for *any* state, even ones we haven't seen before (and how could that be accurate?). This whole process, if we are able to be more and more accurate, is known as **generalisation**.


#### Environment


In [3]:
class HomepageEnv:
    def __init__(self):
        self.contexts = ["New viewer", "Subscriber"]
        self.actions = ["🔥 Viral thing", "🤖 AI tutorial", "💤 Boring politics debate"]
        self.num_contexts = len(self.contexts)
        self.num_actions = len(self.actions)

    def get_reward(self, context_idx, action_idx):
        # New viewers (context 0) are attracted by viral videos
        if context_idx == 0: # the index for a new viewer
            true_probs = [0.6, 0.1, 0.05] # gives the size of a spinning wheel, here "viral thing" has 60% of the space 
            return 1 if np.random.rand() < true_probs[action_idx] else 0 # like spinning a wheel that can land anywhere from 0.00 to 0.99
        # Subscribers (context 1) want deeper content
        elif context_idx == 1:
            true_probs = [0.1, 0.5, 0.7] # The subscribers are thoughtfull and use YouTube a bit differently, they want boring debates
            return 1 if np.random.rand() < true_probs[action_idx] else 0

# Initialize environment
env = HomepageEnv()

In [4]:
env.contexts

['New viewer', 'Subscriber']

In [5]:
env.actions

['🔥 Viral thing', '🤖 AI tutorial', '💤 Boring politics debate']


#### Building: the device


In [6]:
# what's the simplest possible function that we can build? Let's try just a linear thing
# So, let's represent our context as a list
new_viewer = [1, 0] # just a one representing the type of person that has arrived at our YouTube page
subscriber = [0, 1] # the same for this type of user

In [7]:
# What do we miss now? If you remember back to our machine learning class, we actually know how to build this
w = np.random.randn(env.num_contexts, env.num_actions)
w

array([[ 0.98827504,  0.99093931, -1.42083327],
       [ 0.63843579, -0.07698662, -0.68891338]])

In [8]:
# We can now estiamte the value, by taking our weights and multiply them with our featues
np.array(new_viewer) @ w     # (1, 2) x (2, 3) -> (1, 3)

array([ 0.98827504,  0.99093931, -1.42083327])

In [9]:
# In the same way, we can estimate the values from our subscribers
np.array(subscriber) @ w

array([ 0.63843579, -0.07698662, -0.68891338])

So, by estimating our values in this manner, you see that we 'pluck out' the rows for that type of person we are actually interested in, by dot-producting with a feature vector that is 1, if this is the user we are about, and 0 otherwise. 

In [10]:
# so all that we need from our state representation is now 
state = np.zeros(env.num_contexts)
state

array([0., 0.])

In [11]:
# so, a user shows up
np.random.randint(0, env.num_contexts) # get a random number between 0 and 1

0

In [12]:
# and we set the feature to be 1, for this type of user that has showed up
state[np.random.randint(0, env.num_contexts)] = 1
state

array([0., 1.])

In [130]:
# now to get the estimates of what we should how to this user, we can just get the correct row by the dot product
correct_row_with_probs = state @ w
correct_row_with_probs

array([-0.63579846,  0.39491446, -1.471798  ])

In [132]:
np.argmax(correct_row_with_probs).item()

1

Let's forget about all the details for a moment and focus on one **single event**.

Imagine we see a new viewer (context = [1, 0]). It uses it's current dials to calcualte the estimates CTRs an gets:
y_pred = [0.4, 0.1, 0.2]

Based on this, it chooses the best action (as we have seen in the eprevious lecture, with the argmax), so `action_idx = 0` because in the list 0.4 has the highest value, and it is located at index 0. We then show the '🔥 Viral thing' thumbnail and the user clicks! The agent recieves a **real-world result**: `reward = 1`

So, now we are faced with a simple fact:

1. Our dials was set up such that we thought the click-through rate was 0.4
2. the reality was better than this, we got 1.

So, the difference between reality and what we thought the reality was: `reality - y_pred = 1 - 0.4 = 0.6`. This is our error.

In some sense, it was too pessimistic. How can we adjust our <span style="color:purple">dials</span> (*w*) so that if we find ourself in this exact situation again, our thinking will be more like what we have actually experienced now? I.e., a little bit closer to 1?

Well, we actually know this from our ML course! Supervised learning! Gradient descent! WOOOHO :))

So, we know that to nudge the weight in a direction that reduces our error, we need to multiply by the gradient of our function approximator. So, what is the gradient? Well, our function approximator is pretty easy since it is just linear in the weights, so we have: y_pred = s @ w -> derror/dw = **s**. So our gradient is just the <span style="color:blue">state</span> list. 

So, we use supervised learning. So our update rule becomes
<div style="border: 2px solid #988558; padding: 10px; border-radius: 8px; background-color: #EADDCA;">
<b>w_new </b> <-- old_w + little_bit * error * s
</div>


And this little bit is called the 'learning rate'. This just mean we don't want to step too far, risking overshooting our target.

See that we introduced a new word there: the <span style="color:goldenrod">target</span>. What do we mean by target? Well, the <span style="color:aquamarine">environment</span> gives back sort of a "reality check". We just call this reality check *something*, and that is the target. 

Remember from supervised learning, our estimate of the best click-through-rate (CTR) now fully depends on W. These are, like in supervised learning dials we can turn now, and if we are lucky, potentially get them to some values that is right no matter what. 

However, we don't know in advanve what these values *should be*, so we need to **train those dials up** to give us the <span style="color:green">right answer</span>. And the *way we do that is where the <span style="color:coral">reinforcement learning</span>* comes in. 


#### Let's build it


In [15]:
W = np.zeros((env.num_contexts, env.num_actions))

epsilon = 0.1
num_steps = 20000
#alpha = 0.06
history_linear = []

for step in range(num_steps):
    # 1. Input (X): Get context (random person shows up), and represent this as 1 in our state list (feature vector)
    context_idx = np.random.randint(0, env.num_contexts)
    s = np.zeros(env.num_contexts)
    s[context_idx] = 1

    # 2. Make a prediction (y_pred) - guess the CTRs for this user - with our weights at this moment
    ctr_guess = s @ W

    # 3. Choose an action
    if np.random.rand() < epsilon:
        action_idx = np.random.randint(0, env.num_actions)
    else:
        action_idx = np.argmax(ctr_guess)

    # 4. Find the 'true' label (i.e., y in supervised learning)
    reward = env.get_reward(context_idx, action_idx)
    history_linear.append((context_idx, action_idx, reward))
    target = reward

    # 5. Calculate the 'error' for the action we took
    y_pred = ctr_guess[action_idx]   # based on our predicted ctrs, we choose an action
    error = target - y_pred           # this generates an error signal - if we were wrong

    # 6. Update the weights with gradient descent (known from supervised learning and ML)
    W[:, action_idx] += error * s # Remember that the weight that contributed to this action is found in the column 'action_idx'
    # so we update the entire column, but s is [0, 1], for example, so we only add to the weight that was active, or contributed
    # the rest gets error * 0 = 0 -> old_weight + 0 = old_weight. Simple as that.

# --- Analysis ---
print("--- Scalebandit results ---")
print(f"Final weight matrix (W):\n{np.round(W, 2)}\n")

avg_reward_linear = np.mean([example[2] for example in history_linear])
print(f"Average CTR achieved: {avg_reward_linear:.2%}")

print("\nLet's test our trained 'weights':")
s_new_viewer = np.array([1, 0])
s_subscriber = np.array([0, 1])

# The learned values should approximate the true CTRs!
# True CTRs for New Viewer: [0.6, 0.1, 0.05]
# True CTRs for Subscriber: [0.1, 0.5, 0.7]
print(f"Predictions for new viewer: {s_new_viewer @ W}")
print(f"Predictions for subscriber: {s_subscriber @ W}")

--- Scalebandit results ---
Final weight matrix (W):
[[1. 0. 0.]
 [0. 0. 1.]]

Average CTR achieved: 36.63%

Let's test our trained 'weights':
Predictions for new viewer: [1. 0. 0.]
Predictions for subscriber: [0. 0. 1.]


Woops, that was not good. Click-through is roughly only 37%. That's barely beating *Youbandit* at 33.85% and way off *Personalbandit* at 62.85%. What gives?




##### Fixing a bug: an agent with no memory
--- 
Scalebandit results with **no** <span style="color:purple">learning rate</span>
 Final weight matrix (W):

[[0. 0. 0.]
 [1. 0. 0.]]

Average CTR achieved: **37.28%**

Trained 'weights':

- Predictions for new viewer: [0. 0. 0.]
- Predictions for subscriber: [1. 0. 0.]

 ---

 Scalebandit results **with** <span style="color:purple">learning rate</span>

Final weight matrix (W):
[[0.45 0.08 0.03]
 [0.03 0.51 0.71]]

Average CTR achieved: **61.61%**

Trained 'weights':
- Predictions for new viewer: [0.45448043 0.07525964 0.03243021]
- Predictions for subscriber: [0.03078805 0.50880286 0.71027821] 

So, why is this? 

If you think back to the last lecture, we used this "sample-average" method to update our belief table. The more we saw an example and got to choose an action, the less extreme the update got. So over time, the updates was very small and incremental in the end. We had this thing `1 / action_counts[action_idx]` before the difference of the reward and the estimated value. We could essentially call this this something like a *learning rate*. This learning rate acts as a built in *memory management system*. Early on, the agent has little experience, so it has a high *learning rate*. It's pretty aggressive, and it learns what it can from new information because it doesn't know any better. Later on (high N), the agent has *a lot of experience* for that state-action pair, so it treats new information as just one more data point, make only a tiny adjustment to its already-confident belief.  

Why do we need a learning rate at all? Because it allows our beliefs to 'land' in a way (converge to the true average technically). In the end, you have to decide on something, so you should not jump around too much. A high learning rate is the equivalent of jumping around a lot - never deciding if you think these are the true values or not. 

---

So why didn't we use the same sample average method or 1/N or whatever for *Scalebandit*?

The explenation is slightly technical, and the reason is that we wanted to make our *Personalbandit* general. And more general means being able to tackle **all** problems it could potentially encouter. In our YouTube <span style="color:#6F8FAF">**environment**</span> the *hidden secret* never changed. It had the values locked down. They were written in stone so to speak. Never, ever changing. However, most real-world problems are not like that. They are what is called as **<span style="color:red">non-</span>stationary**. What if user preferences of what thumbnails they like to see change over time (e.g., a viral video because old news, so it is not interesting longer)? Or maybe you play a game, the opponent change their strategy. We want to be able to solve all kinds of problems with our method. And using the sample average method, having your *learning rate* decay to near-zero is not beneficial. Then you never update yourself! You just run some trajectories, then "Yepp, OKAY, now I know everything I ever need to know". So we want somethign that is more general, and a common approach in modern RL is to use a constant, but quite small, *learning rate*.

This make it so that the agent can "forget" old, outdated information and constantly <span style="color:#00A36C">adapt</span> to new realities, or what videos are viral at any point, at least over time. 

In [42]:
# Let's expand our error not using a learning rate and just see if this create a running average
#W[:, action_idx] += (target - prediction) * s
W[:, action_idx] += (1 - (s @ W[:, action_idx])) * s # toggle the reward between 0 and 1 to see what happens

In [43]:
W[:, action_idx]

array([1., 0.])


##### learning from single samples


In [ ]:
# lets make this tangible. we are going to zoom in on a single part of our agents brain: the weight `W[0, 0]'
# what does this weight represent? It is responsible for the prediction ("new_viewer", "viral thing")

In [44]:
import ipywidgets as widgets
from IPython.display import display
import time

ModuleNotFoundError: No module named 'ipywidgets'


##### A lookup table is a special form of linear function approximation

Let's show this relationship. The idea is pretty huge, because it birdges to what we did last lecture. It means we didn't **throw away our old method**, we <span style="color:#088F8F">generalized it</span>. 